# Generated by Django 4.1.3 on 2022-11-15 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('dept', models.IntegerField()),
                ('needPR', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='NormalPR',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('status', models.TextField()),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr.employee')),
            ],
            options={
                'db_table': 'normalPR',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.TextField()),
                ('next', models.TextField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='ProjectPR',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('belongProject', models.TextField()),
                ('content', models.TextField()),
                ('status', models.TextField()),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr.employee')),
            ],
            options={
                'db_table': 'projectPR',
            },
        ),
        migrations.CreateModel(
            name='ProjectReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.IntegerField()),
                ('point', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr.projectpr')),
            ],
            options={
                'db_table': 'projectReviewRecord',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pid', models.TextField()),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr.employee')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='NormalReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.IntegerField()),
                ('point', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr.normalpr')),
            ],
            options={
                'db_table': 'normalReviewRecord',
            },
        ),
    ]
