# Generated by Django 4.1.3 on 2022-11-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='donePR',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='needPR',
            field=models.BooleanField(),
        ),
    ]
