# Generated by Django 4.1.3 on 2022-11-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0002_employee_donepr_alter_employee_needpr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='donePR',
            new_name='doneNormalPR',
        ),
        migrations.AddField(
            model_name='employee',
            name='doneProjectPR',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
