# Generated by Django 4.1.3 on 2022-11-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0003_rename_donepr_employee_donenormalpr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalpr',
            name='content',
        ),
        migrations.AddField(
            model_name='normalpr',
            name='content1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='normalpr',
            name='content2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='normalpr',
            name='content3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='normalpr',
            name='content4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectpr',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
