# Generated by Django 4.1.3 on 2022-11-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0005_alter_employee_doneprojectpr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='doneProjectPR',
        ),
        migrations.AddField(
            model_name='project',
            name='done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='pdone',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
