# Generated by Django 4.1.3 on 2022-11-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0006_remove_employee_doneprojectpr_project_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pname',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
