# Generated by Django 4.1.3 on 2022-11-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0008_alter_projectpr_belongproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pname',
            new_name='pmid',
        ),
    ]
