# Generated by Django 4.1.3 on 2022-11-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0010_supervisorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpr',
            name='belongProject',
            field=models.TextField(),
        ),
    ]
