# Generated by Django 4.1.3 on 2022-11-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0011_alter_projectpr_belongproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalpr',
            old_name='content1',
            new_name='coordination',
        ),
        migrations.RenameField(
            model_name='normalpr',
            old_name='content2',
            new_name='learning',
        ),
        migrations.RenameField(
            model_name='normalpr',
            old_name='content3',
            new_name='workAmount',
        ),
        migrations.RenameField(
            model_name='normalpr',
            old_name='content4',
            new_name='workQuality',
        ),
        migrations.RenameField(
            model_name='projectpr',
            old_name='content',
            new_name='workDirection',
        ),
        migrations.AddField(
            model_name='normalreviewrecord',
            name='content',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpr',
            name='proportion',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpr',
            name='workProject',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectreviewrecord',
            name='content',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='normalreviewrecord',
            name='point',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectreviewrecord',
            name='point',
            field=models.TextField(),
        ),
    ]
