# Generated by Django 4.1.3 on 2022-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0012_rename_content1_normalpr_coordination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalreviewrecord',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='normalreviewrecord',
            name='point',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectpr',
            name='proportion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectreviewrecord',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectreviewrecord',
            name='point',
            field=models.TextField(blank=True),
        ),
    ]
