# Generated by Django 4.1.3 on 2022-11-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0013_alter_normalreviewrecord_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisorinfo',
            old_name='position',
            new_name='dept',
        ),
    ]
