# Generated by Django 4.1.3 on 2022-11-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0014_rename_position_supervisorinfo_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pdone',
        ),
    ]
