# Generated by Django 4.1.3 on 2022-11-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0015_remove_project_pdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectreviewrecord',
            name='proportion',
            field=models.TextField(blank=True),
        ),
    ]
