# Generated by Django 4.1.3 on 2022-11-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0016_project_pname_projectreviewrecord_proportion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='now',
            new_name='deptCode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='next',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='normalpr',
            name='score',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpr',
            name='score',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
