# Generated by Django 4.1.3 on 2022-11-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0017_rename_now_order_deptcode_rename_next_order_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deptCode',
            new_name='dept',
        ),
    ]
