# Generated by Django 4.1.3 on 2022-11-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0018_rename_deptcode_order_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.TextField(),
        ),
    ]
