# Generated by Django 4.1.3 on 2022-11-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0019_alter_employee_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oreddasd',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
