# Generated by Django 4.1.3 on 2022-11-25 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0020_order_oreddasd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oreddasd',
        ),
    ]
