# Generated by Django 4.1.3 on 2022-11-25 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0021_remove_order_oreddasd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pid',
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectpr',
            name='belongProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr.project'),
        ),
        migrations.AlterField(
            model_name='supervisorinfo',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr.order'),
        ),
    ]
