# Generated by Django 4.1.3 on 2022-11-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0022_remove_order_dept_remove_project_pid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorinfo',
            name='dept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='pr.order'),
        ),
        migrations.AlterField(
            model_name='supervisorinfo',
            name='eid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='pr.employee'),
        ),
    ]
