# Generated by Django 4.1.3 on 2022-11-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0024_employee_creditstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dasdsa',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
