# Generated by Django 4.1.3 on 2022-11-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0025_employee_dasdsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dasdsa',
        ),
    ]
