# Generated by Django 4.1.3 on 2022-11-28 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0027_creditrecord_creditdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialLeave', models.TextField(blank=True)),
                ('sickLeave', models.TextField(blank=True)),
                ('sickLeavePercentage', models.TextField(blank=True)),
                ('personalLeave', models.TextField(blank=True)),
                ('personalLeavePercentage', models.TextField(blank=True)),
                ('marriageLeave', models.TextField(blank=True)),
                ('bereavementLeave', models.TextField(blank=True)),
                ('maternityLeave', models.TextField(blank=True)),
                ('publicLeave', models.TextField(blank=True)),
                ('absenteeism', models.TextField(blank=True)),
                ('absenteeismPercentage', models.TextField(blank=True)),
                ('commendation', models.TextField(blank=True)),
                ('commendationPercentage', models.TextField(blank=True)),
                ('minorMerit', models.TextField(blank=True)),
                ('minorMeritPercentage', models.TextField(blank=True)),
                ('majorMerit', models.TextField(blank=True)),
                ('majorMeritPercentage', models.TextField(blank=True)),
                ('petition', models.TextField(blank=True)),
                ('petitionPercentage', models.TextField(blank=True)),
                ('minorDemerit', models.TextField(blank=True)),
                ('minorDemeritPercentage', models.TextField(blank=True)),
                ('majorDemerit', models.TextField(blank=True)),
                ('majorDemeritPercentage', models.TextField(blank=True)),
                ('attendanceScore', models.TextField(blank=True)),
                ('eid', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='pr.employee')),
            ],
            options={
                'db_table': 'attendanceRecord',
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('status', models.TextField()),
                ('giveDept', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr.order')),
            ],
            options={
                'db_table': 'annotation',
            },
        ),
    ]
