# Generated by Django 4.1.3 on 2022-11-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0028_attendancerecord_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pid',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
