# Generated by Django 4.1.3 on 2022-11-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0029_project_pid_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalreviewrecord',
            name='done',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectreviewrecord',
            name='done',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
