# Generated by Django 4.1.3 on 2022-11-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0030_normalreviewrecord_done_projectreviewrecord_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalreviewrecord',
            name='done',
            field=models.TextField(),
        ),
    ]
