# Generated by Django 4.1.3 on 2022-11-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0031_alter_normalreviewrecord_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalreviewrecord',
            name='done',
        ),
        migrations.RemoveField(
            model_name='projectreviewrecord',
            name='done',
        ),
        migrations.AddField(
            model_name='normalpr',
            name='done',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpr',
            name='done',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
