# Generated by Django 4.1.3 on 2022-11-30 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0032_remove_normalreviewrecord_done_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbleToCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('able', models.BooleanField()),
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='pr.order')),
            ],
            options={
                'db_table': 'ableToCredit',
            },
        ),
    ]
