# Generated by Django 4.1.3 on 2022-11-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0033_abletocredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditdistribution',
            name='giveDept',
            field=models.TextField(),
        ),
    ]
