# Generated by Django 4.1.3 on 2022-12-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0034_alter_creditdistribution_givedept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
