# Generated by Django 4.1.3 on 2022-12-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0035_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorinfo',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr.employee'),
        ),
    ]
